FROM golang:1.16

WORKDIR /usr/src/app

COPY /material-applications/example-backend/ ./

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000

ENV PORT=8080

RUN go build

CMD [ "./server" ]

#commands
#git clone git@github.com:docker-hy/material-applications.git
#docker build . -f Dockerfile.backend -t "backend_exercise14"
#docker run -p 8080:8080 backend_exercise14
